# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora de llegadas')),
            ],
            options={
                'verbose_name': 'Tiempo de llegada',
                'verbose_name_plural': 'Tiempos de llegada',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Código del bus')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orígen'),
        ),
        migrations.AddField(
            model_name='station',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Rutas'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Rutas'),
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Bus', verbose_name='Bus'),
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Station', verbose_name='Estación'),
        ),
    ]
