# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0003_auto_20171105_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.ArrivalTime', verbose_name='Tiempo de llegada')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Ruta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
            },
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='station',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Ruta'),
        ),
    ]
