# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20171105_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Station', verbose_name='Estación actual de usuario'),
        ),
    ]
